FROM python:3.12-slim

WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install selenium webdriver-manager beautifulsoup4 lxml

COPY scraper.py /app/

CMD ["python", "scraper.py", "-t", "CBA", "ANZ"]
